import Head from 'next/head'
import Layout from '../components/Layout'
import { BasketProvider } from '../context/basketContext'
import '../styles/globals.css'

function MyApp({ Component, pageProps }) {
  return (
    <>
    <Head>
        <title>Flower Bouquet</title>
        <meta name="description" content="Generated by create aleyna" />
        <link rel="icon" href="/cicek.png" />
    </Head>

    <BasketProvider>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </BasketProvider>

  </>
  )
}

export default MyApp
